#ARDUINODIR is the path to where you have installed the Arduino software.
#BOARD tells the script what type of Arduino you want to build for and upload to.
#SERIALDEV is the POSIX device name of the serial device that represents your attached Arduino.

ARDUINODIR := ~/prog/arduino-1.0.5
BOARD := uno
SERIALDEV := /dev/ttyACM0

ARDUINODEVEL := ../..

include $(ARDUINODEVEL)/master.mk